import { test, expect } from "vitest";
import { tokenize } from '../src/index.js';

test('example', () => {
    const input = 'console.log("", ``, 1/2, 1, 1e10, 1.23, -1, -1e10, -1.23,\r\n`a${1}b${this.#private}`, /**/ /nice[0-9]\{.\\[/, 0x1Fn)';
    expect(tokenize(input)).toEqual([
        "console",
        ".",
        "log",
        "(",
        "\"\"",
        ",",
        " ",
        "`",
        "`",
        ",",
        " ",
        "1",
        "/",
        "2",
        ",",
        " ",
        "1",
        ",",
        " ",
        "1e10",
        ",",
        " ",
        "1.23",
        ",",
        " ",
        "-",
        "1",
        ",",
        " ",
        "-",
        "1e10",
        ",",
        " ",
        "-",
        "1.23",
        ",",
        "\r\n",
        "`",
        "a",
        "${",
        "1",
        "}",
        "b",
        "${",
        "this",
        ".",
        "#private",
        "}",
        "`",
        ",",
        " ",
        "/**/",
        " ",
        "/nice[0-9]{.\\[/",
        ",",
        " ",
        "0x1Fn",
        ")",
    ]);

})
